---
- name: Scale up resources
  hosts: test
  environment:
    KUBECONFIG: "/root/.kube/config"
  vars:
    namespace: robot-shop
    command:
      - "stress"
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
    label: "app: robot-shop"
    name: app-review
    image: polinux/stress

  tasks:
    - name: Get the status of app-review pod in robot-shop namespace and register output in var pod_info
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        label_selectors:
          - app=robot-shop
        namespace: "{{ namespace }}"
        name: app-review
      register: pod_info

    - name: Display the pod_info
      ansible.builtin.debug:
        var: pod_info

    - name: Delete pod app-review in robot-shop namespace
      kubernetes.core.k8s:
        state: absent
        api_version: v1
        kind: Pod
        label_selectors:
          - app=robot-shop
        namespace: "{{ namespace }}"
        name: app-review

    - name: Wait for 60 sec
      ansible.builtin.wait_for:
        timeout: 60

    - name: Create app-review pod using a container from image var with memory resource request 150Mi and limit as 200Mi and var command and args
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: app-review
            namespace: "{{ namespace }}"
          spec:
            containers:
              - name: app-review
                image: "{{ image }}"
                resources:
                  requests:
                    memory: 150Mi
                  limits:
                    memory: 200Mi
                command: "{{ command }}"
                args: "{{ args }}"
